#!/bin/bash

##
## itcss-easy
##
## builds a folder structure based on ITCSS conventions.
##
## application.scss file will be generated with proper import
## structure for each scss directory.
##
## components can be built from the command line by passing the
## component name as an argument.


COMMAND='itcss-easy'
ERROR='\033[0;31m'
NC='\033[0m' # No Color
SUCCESS='\033[0;32m'

## ITCSS layers
layers=(settings tools generic elements objects components trumps)

## Prompt user for stylesheet name and build stylesheet
function create_stylesheet {
  printf "Enter a name for your new global stylesheet. It will be appended with a .scss file extension.\nOr, leave the name blank and an application.scss file will be created for you.\n"
  read stylesheet_prompt_val
  stylesheet=''
  if [ "${stylesheet_prompt_val}" == "" ]; then
    stylesheet='application'
  else
    stylesheet=${stylesheet_prompt_val}
  fi
}

## creates a component
function create_component {
  touch "components/_${1}.scss"
  echo "@import" "\"${1}"\"";" >> components/components.scss
  printf "${SUCCESS}Your new component ${1} has been created\n"
}

## sets up ITCSS folder structure & builds stylesheet.
## should be run first before trying to create a component
function init {
  create_stylesheet
  for i in "${layers[@]}"
  do
     :
     mkdir $i && touch $i/$i".scss"
     echo "@import" "\"${i}/${i}"\"";" >> ${stylesheet}.scss
  done
  printf "${SUCCESS}You're all setup! ITCSS directories and a new global stylesheet ${stylesheet}.scss have been created\n"
}

## if argument is false, run init function
## if argument is true, build component
if [ "$1" != "" ]; then
  #check for a components.scss file before building component
  if [ -f "components/components.scss" ]; then
    create_component $1
  else
    printf "${ERROR}Woops, you don't have a components directory. Try running ${COMMAND} to get setup\n"
  fi
else
  init
fi
