#!/bin/bash

##
## itcss-scss
##
## builds a folder structure based on ITCSS conventions.
##
## an application.scss file will be generated with the proper import
## structure for each of the directories.
##
## components can be built from the command line by passing the
## component name as an argument.
## example: itcss-scss [component-name]


clear ## clear terminal
touch application.scss ## make an application.scss file

layers=(settings tools generic elements objects components trumps)

if [ "$1" != "" ]; then
  ## create components by passing a name argument.
  ## itcss-scss [component-name]
  mkdir "components/${1}" && touch "components/${i}/${i}.scss"
  echo "@import" "${i};" >> components/components.scss
  echo "Your new component $1 has been created"

else
  ## creates a folder and .scss file for each ITCSS layer
  ## imports each .scss file into an application.scss file
  for i in "${layers[@]}"
  do
     :
     mkdir $i && touch $i/$i".scss"
     echo "@import" "\"${i}/${i}"\"";" >> application.scss
  done
fi
